const { chromium } = require('playwright')
const assert = require('node:assert/strict')
const base = process.env.SITE_TEST_URL || 'http://127.0.0.1:5173'
;(async () => {
  const { preview } = await import('vite')
  const server = process.env.SITE_TEST_URL ? null : await preview({preview:{host:'127.0.0.1',port:5173,strictPort:true}})
  const browser = await chromium.launch({headless:true, executablePath:process.env.CHROMIUM_PATH || undefined, args:['--no-sandbox', '--disable-dev-shm-usage']})
  const page = await browser.newPage({viewport:{width:1440,height:1000}})
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  const badAssets = []
  page.on('response', r => { if(r.url().startsWith(base) && r.status() >= 400) badAssets.push(r.url()) })
  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({width, height:1000})
    for (const route of ['/', '/about', '/projects', '/experience', '/speaking', '/photography', '/contact', '/missing']) {
      await page.goto(base+route)
      await page.locator('h1').waitFor()
      await page.evaluate(async () => {
        document.documentElement.style.scrollBehavior = 'auto'
        for(let y=0;y<document.body.scrollHeight;y+=500) { window.scrollTo(0,y); await new Promise(r=>setTimeout(r,35)) }
      })
      await page.waitForTimeout(150)
      assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth+1), `overflow: ${route} at ${width}`)
      assert(await page.locator('h1').count() === 1, `heading count ${route}`)
      const images = await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.complete && !i.naturalWidth).map(i=>i.src))
      assert.deepEqual(images, [], `broken images ${route}`)
    }
  }
  await page.setViewportSize({width:1440,height:1000})
  await page.goto(base+'/projects')
  await page.locator('.work-card').first().click()
  await page.getByRole('dialog', {name:/Case study/}).waitFor()
  assert(await page.evaluate(()=>document.body.style.overflow==='hidden' && document.getElementById('root').inert))
  await page.keyboard.press('Control+k')
  await page.getByRole('combobox').fill('nonsense')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  assert.equal(await page.locator('.cmdk-empty').count(),1)
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('.cmdk').count(),0)
  assert.equal(await page.locator('.drawer').count(),1)
  assert(await page.evaluate(()=>document.body.style.overflow==='hidden'))
  await page.keyboard.press('Escape')
  assert(await page.evaluate(()=>!document.getElementById('root').inert && document.body.style.overflow !== 'hidden'))
  await page.goto(base+'/photography')
  await page.locator('.photo-expand').first().click()
  await page.keyboard.press('ArrowLeft')
  assert((await page.locator('.lightbox-count').textContent()).includes('17 / 17'))
  await page.keyboard.press('Tab')
  assert(await page.evaluate(()=>document.activeElement.closest('.photo-lightbox') !== null))
  await page.keyboard.press('Escape')
  await page.goto(base+'/about')
  await page.getByRole('tab').first().click()
  await page.keyboard.press('ArrowRight')
  assert.equal(await page.getByRole('tab').nth(1).getAttribute('aria-selected'),'true')
  await page.getByRole('slider',{name:'Scrub trajectory year'}).fill('4')
  assert.equal(await page.locator('.traj-dot-btn').last().getAttribute('aria-current'),'true')
  await page.goto(base+'/experience')
  await page.locator('.filter-bar button').nth(1).click()
  assert.equal(await page.locator('.filter-bar button').nth(1).getAttribute('aria-pressed'),'true')
  await page.locator('.bs-skill').first().click()
  assert(await page.locator('.bs-evidence-item').count() > 0)
  await page.goto(base+'/projects')
  await page.locator('.cst-node').first().click()
  assert.equal(await page.locator('.cst-node').first().getAttribute('aria-pressed'),'true')
  await page.goto(base+'/contact')
  await page.evaluate(()=>Object.defineProperty(navigator, 'clipboard', {value:{writeText:()=>Promise.reject(new Error('denied'))},configurable:true}))
  await page.locator('.copy-email').click()
  assert(!(await page.locator('.copy-email').textContent()).includes('Copied'))
  let posts = 0
  await page.route('https://formspree.io/**', async route => { posts++; await new Promise(r=>setTimeout(r,250)); await route.fulfill({status:200,contentType:'application/json',body:'{}'}) })
  await page.getByLabel('Name',{exact:true}).fill('Test')
  await page.getByLabel('Email',{exact:true}).fill('test@example.com')
  await page.getByLabel('Subject',{exact:true}).fill('Test subject')
  await page.getByLabel('Message',{exact:true}).fill('Automated test message; no email sent.')
  await page.getByRole('button',{name:'Send message',exact:true}).click()
  assert.equal(await page.getByRole('button',{name:'Sending…',exact:true}).isDisabled(),true)
  await page.locator('.status').filter({hasText:'Your message has been sent'}).waitFor()
  assert.equal(posts,1)
  await page.locator('.accordion-trigger').first().click()
  assert.equal(await page.locator('.accordion-trigger').first().getAttribute('aria-expanded'),'true')
  await page.setViewportSize({width:390,height:844})
  await page.goto(base+'/')
  await page.getByRole('button',{name:'Open menu',exact:true}).click()
  assert(await page.evaluate(()=>document.getElementById('root').inert))
  await page.getByRole('dialog',{name:'Navigation'}).getByRole('link',{name:/Projects/}).click()
  await page.waitForURL('**/projects')
  assert(await page.evaluate(()=>!document.getElementById('root').inert))
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto(base+'/projects')
  const clipped = await page.locator('.section h2').evaluateAll(els=>els.some(el=>getComputedStyle(el).clipPath!=='none'))
  assert(!clipped, 'headings clipped under reduced motion')
  await page.goto(base+'/#trajectory')
  await page.waitForURL('**/about#trajectory')
  await page.emulateMedia({reducedMotion:'no-preference'})
  await page.setViewportSize({width:1440,height:1000})
  await page.goto(base+'/')
  await page.getByRole('button',{name:'Pause animations'}).click()
  assert.equal(await page.locator('html').getAttribute('data-motion'),'paused')
  await page.getByRole('link',{name:'Explore my work'}).click()
  await page.waitForURL('**/projects')
  assert.equal(await page.locator('.page-head h1').evaluate(el=>getComputedStyle(el).opacity),'1')
  await page.getByRole('button',{name:'Resume animations'}).click()
  await page.goto(base+'/')
  await page.waitForTimeout(1600)
  await page.screenshot({path:'/tmp/jerry-desktop.png',fullPage:false})
  await page.getByRole('button',{name:'Toggle theme'}).click()
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light')
  await page.waitForTimeout(600)
  await page.screenshot({path:'/tmp/jerry-light.png',fullPage:false})
  await page.setViewportSize({width:390,height:844})
  await page.evaluate(()=>localStorage.setItem('jh-theme','dark'))
  await page.goto(base+'/')
  await page.waitForTimeout(1200)
  await page.screenshot({path:'/tmp/jerry-mobile.png',fullPage:true})
  assert.deepEqual(errors,[], 'browser errors')
  assert.deepEqual(badAssets,[], 'HTTP errors')
  console.log('PASS: 32 route/viewport checks; dialogs, nested scroll locks, keyboard navigation, gallery wrap, contact validation/submission, clipboard failure, themes, legacy links, reduced motion and assets.')
  await browser.close()
  if (server) await new Promise(resolve => server.httpServer.close(resolve))
})().catch(e=>{console.error(e);process.exit(1)})
